DECLARE @reportname as varchar(100)
SET reportname = "rpi-test-image-raspberrypi4-64.rootfs-20250106124937.json";

-- Select Packages Unpached only
SELECT P.*, 
(SELECT 
 COUNT(NC.ID) FROM NVD NC, Issues I 
 WHERE NC.ID=I.NVDID AND I.PackageID=P.ID AND I.Status='Unpatched' 
 AND ((CAST(NC.SCOREV4 AS NUMERIC)>=9.0) OR 
      (CAST(NC.SCOREV4 AS NUMERIC)<0.1 AND CAST(NC.SCOREV3 AS NUMERIC)>=9.0) OR 
	  (CAST(NC.SCOREV4 AS NUMERIC)<0.1 AND CAST(NC.SCOREV3 AS NUMERIC)<0.1 AND CAST(NC.SCOREV2 AS NUMERIC)>=9.0))) Critical,
(SELECT COUNT(NH.ID) FROM NVD NH, Issues I 
 WHERE NH.ID=I.NVDID AND I.PackageID=P.ID AND I.Status='Unpatched' 
 AND ((CAST(NH.SCOREV4 AS NUMERIC)>=7.0 AND CAST(NH.SCOREV4 AS NUMERIC)<9.0) OR
      (CAST(NH.SCOREV4 AS NUMERIC)<0.1 AND CAST(NH.SCOREV3 AS NUMERIC)>=7.0 AND CAST(NH.SCOREV3 AS NUMERIC)<9.0) OR     
	  (CAST(NH.SCOREV4 AS NUMERIC)<0.1 AND CAST(NH.SCOREV3 AS NUMERIC)<0.1 AND CAST(NH.SCOREV2 AS NUMERIC)>=7.0 AND CAST(NH.SCOREV2 AS NUMERIC)<9.0))) High,
(SELECT COUNT(NM.ID) FROM NVD NM, Issues I 
WHERE NM.ID=I.NVDID AND I.PackageID=P.ID AND I.Status='Unpatched' 
 AND ((CAST(NM.SCOREV4 AS NUMERIC)>=4.0 AND CAST(NM.SCOREV4 AS NUMERIC)<7.0) OR     
      (CAST(NM.SCOREV4 AS NUMERIC)<0.1 AND (CAST(NM.SCOREV3 AS NUMERIC)>=4.0 AND CAST(NM.SCOREV3 AS NUMERIC)<7.0)) OR
	  (CAST(NM.SCOREV4 AS NUMERIC)<0.1 AND CAST(NM.SCOREV3 AS NUMERIC)<0.1 AND CAST(NM.SCOREV2 AS NUMERIC)>=4.0 AND CAST(NM.SCOREV2 AS NUMERIC)<7.0))) Medium, 
(SELECT COUNT(NL.ID) 
FROM NVD NL, Issues I 
WHERE NL.ID=I.NVDID AND I.PackageID=P.ID AND I.Status='Unpatched' 
AND ((CAST(NL.SCOREV4 AS NUMERIC)>=0.1 AND CAST(NL.SCOREV4 AS NUMERIC)<4.0) OR     
     (CAST(NL.SCOREV4 AS NUMERIC)<0.1 AND CAST(NL.SCOREV3 AS NUMERIC)>=0.1 AND CAST(NL.SCOREV3 AS NUMERIC)<4.0) OR     
	 (CAST(NL.SCOREV4 AS NUMERIC)<0.1 AND CAST(NL.SCOREV3 AS NUMERIC)<0.1 AND CAST(NL.SCOREV2 AS NUMERIC)>=0.1 AND CAST(NL.SCOREV2 AS NUMERIC)<4.0))) Low,
	 (SELECT COUNT(NN.ID) 
FROM NVD NN, Issues I 
WHERE NN.ID=I.NVDID AND I.PackageID=P.ID AND I.Status='Unpatched' 
AND (CAST(NN.SCOREV4 AS NUMERIC)<0.1 AND CAST(NN.SCOREV3 AS NUMERIC)<0.1 AND CAST(NN.SCOREV2 AS NUMERIC)<0.1)) None,
(SELECT COUNT(NU.ID) FROM NVD NU, Issues I WHERE NU.ID=I.NVDID AND I.PackageID=P.ID AND I.Status='Unpatched') Unpatched, 
(SELECT COUNT(NP.ID) FROM NVD NP, Issues I WHERE NP.ID=I.NVDID AND I.PackageID=P.ID AND I.Status='Patched') Patched, 
(SELECT COUNT(NI.ID) FROM NVD NI, Issues I WHERE NI.ID=I.NVDID AND I.PackageID=P.ID AND I.Status='Ignored') Ignored 
FROM Packages P 
INNER JOIN CVEReports C ON C.ID=P.CVEReportID AND C.FileName = 'rpi-test-image-raspberrypi4-64.rootfs-20250106124937.json' 
WHERE (Critical != 0 OR High != 0 OR Medium != 0 OR Low != 0 OR None != 0) 
GROUP BY P.ID ORDER BY P.ID ASC, Critical DESC, High DESC, Medium DESC, Low DESC, None DESC 
LIMIT 250 OFFSET 0;

-- Select All Packages
SELECT P.*, 
(SELECT 
 COUNT(NC.ID) FROM NVD NC, Issues I 
 WHERE NC.ID=I.NVDID AND I.PackageID=P.ID 
 AND ((CAST(NC.SCOREV4 AS NUMERIC)>=9.0) OR 
      (CAST(NC.SCOREV4 AS NUMERIC)<0.1 AND CAST(NC.SCOREV3 AS NUMERIC)>=9.0) OR 
	  (CAST(NC.SCOREV4 AS NUMERIC)<0.1 AND CAST(NC.SCOREV3 AS NUMERIC)<0.1 AND CAST(NC.SCOREV2 AS NUMERIC)>=9.0))) Critical,
(SELECT COUNT(NH.ID) FROM NVD NH, Issues I 
 WHERE NH.ID=I.NVDID AND I.PackageID=P.ID
 AND ((CAST(NH.SCOREV4 AS NUMERIC)>=7.0 AND CAST(NH.SCOREV4 AS NUMERIC)<9.0) OR
      (CAST(NH.SCOREV4 AS NUMERIC)<0.1 AND CAST(NH.SCOREV3 AS NUMERIC)>=7.0 AND CAST(NH.SCOREV3 AS NUMERIC)<9.0) OR     
	  (CAST(NH.SCOREV4 AS NUMERIC)<0.1 AND CAST(NH.SCOREV3 AS NUMERIC)<0.1 AND CAST(NH.SCOREV2 AS NUMERIC)>=7.0 AND CAST(NH.SCOREV2 AS NUMERIC)<9.0))) High,
(SELECT COUNT(NM.ID) FROM NVD NM, Issues I 
WHERE NM.ID=I.NVDID AND I.PackageID=P.ID
 AND ((CAST(NM.SCOREV4 AS NUMERIC)>=4.0 AND CAST(NM.SCOREV4 AS NUMERIC)<7.0) OR     
      (CAST(NM.SCOREV4 AS NUMERIC)<0.1 AND (CAST(NM.SCOREV3 AS NUMERIC)>=4.0 AND CAST(NM.SCOREV3 AS NUMERIC)<7.0)) OR
	  (CAST(NM.SCOREV4 AS NUMERIC)<0.1 AND CAST(NM.SCOREV3 AS NUMERIC)<0.1 AND CAST(NM.SCOREV2 AS NUMERIC)>=4.0 AND CAST(NM.SCOREV2 AS NUMERIC)<7.0))) Medium, 
(SELECT COUNT(NL.ID) 
FROM NVD NL, Issues I 
WHERE NL.ID=I.NVDID AND I.PackageID=P.ID
AND ((CAST(NL.SCOREV4 AS NUMERIC)>=0.1 AND CAST(NL.SCOREV4 AS NUMERIC)<4.0) OR     
     (CAST(NL.SCOREV4 AS NUMERIC)<0.1 AND CAST(NL.SCOREV3 AS NUMERIC)>=0.1 AND CAST(NL.SCOREV3 AS NUMERIC)<4.0) OR     
	 (CAST(NL.SCOREV4 AS NUMERIC)<0.1 AND CAST(NL.SCOREV3 AS NUMERIC)<0.1 AND CAST(NL.SCOREV2 AS NUMERIC)>=0.1 AND CAST(NL.SCOREV2 AS NUMERIC)<4.0))) Low,
	 (SELECT COUNT(NN.ID) 
FROM NVD NN, Issues I 
WHERE NN.ID=I.NVDID AND I.PackageID=P.ID
AND (CAST(NN.SCOREV4 AS NUMERIC)<0.1 AND CAST(NN.SCOREV3 AS NUMERIC)<0.1 AND CAST(NN.SCOREV2 AS NUMERIC)<0.1)) None,
(SELECT COUNT(NP.ID) FROM NVD NP, Issues I WHERE NP.ID=I.NVDID AND I.PackageID=P.ID AND I.Status='Unpatched') Unpatched, 
(SELECT COUNT(NP.ID) FROM NVD NP, Issues I WHERE NP.ID=I.NVDID AND I.PackageID=P.ID AND I.Status='Patched') Patched, 
(SELECT COUNT(NI.ID) FROM NVD NI, Issues I WHERE NI.ID=I.NVDID AND I.PackageID=P.ID AND I.Status='Ignored') Ignored 
FROM Packages P 
INNER JOIN CVEReports C ON C.ID=P.CVEReportID AND C.FileName = 'rpi-test-image-raspberrypi4-64.rootfs-20250106124937.json' 
WHERE (Critical != 0 OR High != 0 OR Medium != 0 OR Low != 0 OR None != 0) 
GROUP BY P.ID ORDER BY Critical DESC, High DESC, Medium DESC, Low DESC, None DESC 
LIMIT 250 OFFSET 0;


-- Select Count Packages
SELECT COUNT(*) rows FROM 
(SELECT P.ID FROM Packages P, CVEReports C, Issues I 
 WHERE P.CVEReportID=C.ID AND C.FileName = 'rpi-test-image-raspberrypi4-64.rootfs-20250106124937.json' AND I.PackageID = P.ID AND 
 (SELECT COUNT(NC.ID) FROM NVD NC WHERE NC.ID=I.NVDID AND 
  ((CAST(NC.SCOREV4 AS NUMERIC)>=9.0) OR 
   (CAST(NC.SCOREV4 AS NUMERIC)<0.1 AND CAST(NC.SCOREV3 AS NUMERIC)>=9.0) OR 
   (CAST(NC.SCOREV4 AS NUMERIC)<0.1 AND CAST(NC.SCOREV3 AS NUMERIC)<0.1 AND CAST(NC.SCOREV2 AS NUMERIC)>=9.0)) != 0) OR 
  (SELECT COUNT(NH.ID) 
   FROM NVD NH 
   WHERE NH.ID=I.NVDID AND
   ((CAST(NH.SCOREV4 AS NUMERIC)>=7.0 AND CAST(NH.SCOREV4 AS NUMERIC)<9.0) OR
    (CAST(NH.SCOREV4 AS NUMERIC)<0.1 AND CAST(NH.SCOREV3 AS NUMERIC)>=7.0 AND CAST(NH.SCOREV3 AS NUMERIC)<9.0) OR     
	(CAST(NH.SCOREV4 AS NUMERIC)<0.1 AND CAST(NH.SCOREV3 AS NUMERIC)<0.1 AND CAST(NH.SCOREV2 AS NUMERIC)>=7.0 AND CAST(NH.SCOREV2 AS NUMERIC)<9.0)) != 0) OR 
  (SELECT COUNT(NM.ID) 
   FROM NVD NM 
   WHERE NM.ID=I.NVDID AND 
   ((CAST(NM.SCOREV4 AS NUMERIC)>=4.0 AND CAST(NM.SCOREV4 AS NUMERIC)<7.0) OR     
    (CAST(NM.SCOREV4 AS NUMERIC)<0.1 AND (CAST(NM.SCOREV3 AS NUMERIC)>=4.0 AND CAST(NM.SCOREV3 AS NUMERIC)<7.0)) OR
	(CAST(NM.SCOREV4 AS NUMERIC)<0.1 AND CAST(NM.SCOREV3 AS NUMERIC)<0.1 AND CAST(NM.SCOREV2 AS NUMERIC)>=4.0 AND CAST(NM.SCOREV2 AS NUMERIC)<7.0)) != 0) OR 
  (SELECT COUNT(NL.ID) 
   FROM NVD NL 
   WHERE NL.ID=I.NVDID AND 
   ((CAST(NL.SCOREV4 AS NUMERIC)>=0.1 AND CAST(NL.SCOREV4 AS NUMERIC)<4.0) OR     
    (CAST(NL.SCOREV4 AS NUMERIC)<0.1 AND CAST(NL.SCOREV3 AS NUMERIC)>=0.1 AND CAST(NL.SCOREV3 AS NUMERIC)<4.0) OR     
	(CAST(NL.SCOREV4 AS NUMERIC)<0.1 AND CAST(NL.SCOREV3 AS NUMERIC)<0.1 AND CAST(NL.SCOREV2 AS NUMERIC)>=0.1 AND CAST(NL.SCOREV2 AS NUMERIC)<4.0))!= 0) OR
  (SELECT COUNT(NN.ID) 
   FROM NVD NN 
   WHERE NN.ID=I.NVDID AND 
   CAST(NN.SCOREV4 AS NUMERIC)<0.1 AND 
   CAST(NN.SCOREV3 AS NUMERIC)<0.1 AND 
   CAST(NN.SCOREV2 AS NUMERIC)<0.1 != 0) 
AND I.Status='Unpatched' GROUP BY P.ID);

SELECT COUNT(*) rows FROM 
(SELECT P.ID FROM Packages P, CVEReports C, Issues I 
WHERE P.CVEReportID=C.ID AND C.FileName = 'rpi-test-image-raspberrypi4-64.rootfs-20250106124937.json' AND I.PackageID = P.ID
AND I.Status='Unpatched' GROUP BY P.ID);

SELECT COUNT(*) rows FROM 
(SELECT P.ID FROM Packages P, CVEReports C, Issues I 
WHERE P.CVEReportID=C.ID AND C.FileName = 'rpi-test-image-raspberrypi4-64.rootfs-20250106124937.json' AND I.PackageID = P.ID
GROUP BY P.ID);

SELECT COUNT(*) rows FROM 
(SELECT P.ID FROM Packages P, CVEReports C, Issues I 
 WHERE P.CVEReportID=C.ID AND C.FileName = 'rpi-test-image-raspberrypi4-64.rootfs-20250106124937.json' AND I.PackageID = P.ID AND 
 (SELECT COUNT(NC.ID) FROM NVD NC WHERE NC.ID=I.NVDID AND 
  ((CAST(NC.SCOREV4 AS NUMERIC)>=9.0) OR 
   (CAST(NC.SCOREV4 AS NUMERIC)<0.1 AND CAST(NC.SCOREV3 AS NUMERIC)>=9.0) OR 
   (CAST(NC.SCOREV4 AS NUMERIC)<0.1 AND CAST(NC.SCOREV3 AS NUMERIC)<0.1 AND CAST(NC.SCOREV2 AS NUMERIC)>=9.0)) != 0) OR 
  (SELECT COUNT(NH.ID) 
   FROM NVD NH 
   WHERE NH.ID=I.NVDID AND
   ((CAST(NH.SCOREV4 AS NUMERIC)>=7.0 AND CAST(NH.SCOREV4 AS NUMERIC)<9.0) OR
    (CAST(NH.SCOREV4 AS NUMERIC)<0.1 AND CAST(NH.SCOREV3 AS NUMERIC)>=7.0 AND CAST(NH.SCOREV3 AS NUMERIC)<9.0) OR     
	(CAST(NH.SCOREV4 AS NUMERIC)<0.1 AND CAST(NH.SCOREV3 AS NUMERIC)<0.1 AND CAST(NH.SCOREV2 AS NUMERIC)>=7.0 AND CAST(NH.SCOREV2 AS NUMERIC)<9.0)) != 0) OR 
  (SELECT COUNT(NM.ID) 
   FROM NVD NM 
   WHERE NM.ID=I.NVDID AND 
   ((CAST(NM.SCOREV4 AS NUMERIC)>=4.0 AND CAST(NM.SCOREV4 AS NUMERIC)<7.0) OR     
    (CAST(NM.SCOREV4 AS NUMERIC)<0.1 AND (CAST(NM.SCOREV3 AS NUMERIC)>=4.0 AND CAST(NM.SCOREV3 AS NUMERIC)<7.0)) OR
	(CAST(NM.SCOREV4 AS NUMERIC)<0.1 AND CAST(NM.SCOREV3 AS NUMERIC)<0.1 AND CAST(NM.SCOREV2 AS NUMERIC)>=4.0 AND CAST(NM.SCOREV2 AS NUMERIC)<7.0)) != 0) OR 
  (SELECT COUNT(NL.ID) 
   FROM NVD NL 
   WHERE NL.ID=I.NVDID AND 
   ((CAST(NL.SCOREV4 AS NUMERIC)>=0.1 AND CAST(NL.SCOREV4 AS NUMERIC)<4.0) OR     
    (CAST(NL.SCOREV4 AS NUMERIC)<0.1 AND CAST(NL.SCOREV3 AS NUMERIC)>=0.1 AND CAST(NL.SCOREV3 AS NUMERIC)<4.0) OR     
	(CAST(NL.SCOREV4 AS NUMERIC)<0.1 AND CAST(NL.SCOREV3 AS NUMERIC)<0.1 AND CAST(NL.SCOREV2 AS NUMERIC)>=0.1 AND CAST(NL.SCOREV2 AS NUMERIC)<4.0))!= 0) OR
  (SELECT COUNT(NN.ID) 
   FROM NVD NN 
   WHERE NN.ID=I.NVDID AND 
   CAST(NN.SCOREV4 AS NUMERIC)<0.1 AND 
   CAST(NN.SCOREV3 AS NUMERIC)<0.1 AND 
   CAST(NN.SCOREV2 AS NUMERIC)<0.1 != 0) 
AND I.Status='Unpatched' GROUP BY P.ID);

SELECT COUNT(*) rows FROM 
(SELECT P.ID FROM Packages P, CVEReports C, Issues I 
WHERE P.CVEReportID=C.ID AND C.FileName = 'rpi-test-image-raspberrypi4-64.rootfs-20250106124937.json' AND 
I.PackageID = P.ID AND 
I.Status='Unpatched' GROUP BY P.ID);