PRAGMA temp_store = 2;
CREATE TEMP TABLE IF NOT EXISTS _Variables(Name TEXT PRIMARY KEY, RealValue REAL, IntegerValue INTEGER, BlobValue BLOB, TextValue TEXT);
INSERT OR REPLACE INTO _Variables (Name, TextValue) VALUES ('ReportName', 'imx-image-full-imx93evk-20240228162056.rootfs.json');

SELECT P.*,
(SELECT COUNT(NC.ID) FROM NVD NC, Issues I 
WHERE NC.ID=I.NVDID 
AND I.PackageID=P.ID 
AND I.Status='Unpatched' 
AND ((CAST(NC.SCOREV3 AS NUMERIC)>=9.0))) Critical,
(SELECT COUNT(NC.ID) FROM NVD NC, Issues I 
WHERE NC.ID=I.NVDID 
AND I.PackageID=P.ID 
AND I.Status='Unpatched' 
AND ((CAST(N.SCOREV3 AS NUMERIC)>=7.0) AND CAST(N.SCOREV3 AS NUMERIC)<9.0)) High,
(SELECT COUNT(NC.ID) FROM NVD NC, Issues I 
WHERE NC.ID=I.NVDID 
AND I.PackageID=P.ID 
AND I.Status='Unpatched' 
AND ((CAST(N.SCOREV3 AS NUMERIC)>=4.0) AND CAST(N.SCOREV3 AS NUMERIC)<7.0)) Medium,
(SELECT COUNT(NC.ID) FROM NVD NC, Issues I 
WHERE NC.ID=I.NVDID 
AND I.PackageID=P.ID 
AND I.Status='Unpatched' 
AND ((CAST(N.SCOREV3 AS NUMERIC)>=0.1) AND CAST(N.SCOREV3 AS NUMERIC)<4.0)) Low,
(SELECT COUNT(NC.ID) FROM NVD NC, Issues I 
WHERE NC.ID=I.NVDID 
AND I.PackageID=P.ID 
AND I.Status='Unpatched' 
AND (CAST(N.SCOREV3 AS NUMERIC)<0.1)) None
FROM Packages P, Issues I, NVD N, CVEReports C
WHERE C.FileName = (SELECT coalesce(RealValue, IntegerValue, BlobValue, TextValue) FROM _Variables WHERE Name = 'ReportName' LIMIT 1)
AND I.PackageID = P.ID AND I.Status = 'Unpatched'
AND N.ID = I.NVDID
AND C.ID = P.CVEReportID
GROUP BY P.ID
ORDER BY Critical DESC , High DESC, Medium DESC, Low DESC , None DESC;

SELECT COUNT(*) FROM (SELECT P.ID
FROM Packages P, CVEReports C, Issues I
WHERE P.CVEReportID=C.ID AND C.FileName = (SELECT coalesce(RealValue, IntegerValue, BlobValue, TextValue) FROM _Variables WHERE Name = 'ReportName' LIMIT 1) 
AND I.PackageID = P.ID
AND I.Status='Unpatched'
AND 
((SELECT COUNT(NC.ID)
FROM NVD NC
WHERE NC.ID=I.NVDID
AND CAST(NC.SCOREV3 AS NUMERIC)>=9.0) != 0
OR (SELECT COUNT(NH.ID) 
FROM NVD NH
WHERE NH.ID=I.NVDID
AND CAST(NH.SCOREV3 AS NUMERIC)>=7.0 AND CAST(NH.SCOREV3 AS NUMERIC)<9.0) != 0
OR (SELECT COUNT(NM.ID) 
FROM NVD NM
WHERE NM.ID=I.NVDID
AND CAST(NM.SCOREV3 AS NUMERIC)>=4.0 AND CAST(NM.SCOREV3 AS NUMERIC)<7.0) != 0
OR (SELECT COUNT(NL.ID) 
FROM NVD NL
WHERE NL.ID=I.NVDID
AND CAST(NL.SCOREV3 AS NUMERIC)>=0.1 AND CAST(NL.SCOREV3 AS NUMERIC)<4.0) != 0
OR (SELECT COUNT(NN.ID) 
FROM NVD NN
WHERE NN.ID=I.NVDID
AND CAST(NN.SCOREV3 AS NUMERIC)<0.1) != 0)
--AND P.Name LIKE '%linux%'
GROUP BY P.ID);

SELECT P.ID, P.Name, P.Layer, P.Version, I.ID, I.Status, I.NVDID, I.Link, N.ID, CAST(N.SCOREV3 AS NUMERIC) CVSS3Score, N.VECTOR, R.VERSION_END
FROM Packages P, CVEReports C, Issues I, NVD N, Products R
WHERE C.FileName = (SELECT coalesce(RealValue, IntegerValue, BlobValue, TextValue) FROM _Variables WHERE Name = 'ReportName' LIMIT 1) 
AND P.CVEReportID = C.ID
AND I.PackageID = P.ID
AND I.NVDID = N.ID
AND N.ID = R.ID
AND I.Status='Ignored'
ORDER BY P.Name, P.Layer, I.Status, CVSS3Score DESC




SELECT DISTINCT P.ID PID, P.Name, P.Layer, P.Version, I.ID IID, I.Status, I.NVDID, I.Link, CAST(N.SCOREV3 AS NUMERIC) CVSS3Score
FROM Packages P, CVEReports C, Issues I, NVD N
WHERE C.FileName = (SELECT coalesce(RealValue, IntegerValue, BlobValue, TextValue) FROM _Variables WHERE Name = 'ReportName' LIMIT 1) 
AND P.CVEReportID = C.ID
AND I.PackageID = P.ID
AND I.NVDID = N.ID
AND I.Status='Ignored'
ORDER BY P.Name, P.Layer, I.Status, CVSS3Score DESC



SELECT P.ID, P.Name, P.Layer, P.Version, I.ID, I.Status, I.NVDID, I.Link, N.ID, CAST(N.SCOREV3 AS NUMERIC) CVSS3Score, N.VECTOR, R.VERSION_END
FROM Packages P, CVEReports C, Issues I, NVD N, Products R
WHERE C.FileName = (SELECT coalesce(RealValue, IntegerValue, BlobValue, TextValue) FROM _Variables WHERE Name = 'ReportName' LIMIT 1) 
AND P.CVEReportID = C.ID
AND I.PackageID = P.ID
AND I.NVDID = N.ID
AND N.ID = R.ID
AND CVSS3Score >= 7
ORDER BY P.Name, P.Layer, I.Status, CVSS3Score DESC


SELECT * FROM Packages P
INNER JOIN Issues I 
ON I.PackageID=P.ID
INNER JOIN NVD N
ON N.ID=I.NVDID
WHERE P.CVEReportID=1 AND CAST(N.SCOREV3 AS NUMERIC) > 9
AND I.Status='Unpatched'








SELECT COUNT(*) FROM (SELECT P.ID
FROM Packages P, CVEReports C, Issues I
WHERE P.CVEReportID=C.ID AND C.FileName = (SELECT coalesce(RealValue, IntegerValue, BlobValue, TextValue) FROM _Variables WHERE Name = 'ReportName' LIMIT 1) 
AND I.PackageID = P.ID
AND I.Status='Unpatched'
AND 
((SELECT COUNT(NC.ID)
FROM NVD NC
WHERE NC.ID=I.NVDID
AND CAST(NC.SCOREV3 AS NUMERIC)>=9.0) != 0
OR (SELECT COUNT(NH.ID) 
FROM NVD NH
WHERE NH.ID=I.NVDID
AND CAST(NH.SCOREV3 AS NUMERIC)>=7.0 AND CAST(NH.SCOREV3 AS NUMERIC)<9.0) != 0
OR (SELECT COUNT(NM.ID) 
FROM NVD NM
WHERE NM.ID=I.NVDID
AND CAST(NM.SCOREV3 AS NUMERIC)>=4.0 AND CAST(NM.SCOREV3 AS NUMERIC)<7.0) != 0
OR (SELECT COUNT(NL.ID) 
FROM NVD NL
WHERE NL.ID=I.NVDID
AND CAST(NL.SCOREV3 AS NUMERIC)>=0.1 AND CAST(NL.SCOREV3 AS NUMERIC)<4.0) != 0
OR (SELECT COUNT(NN.ID) 
FROM NVD NN
WHERE NN.ID=I.NVDID
AND CAST(NN.SCOREV3 AS NUMERIC)<0.1) != 0)
--AND P.Name LIKE '%linux%'
GROUP BY P.ID);

SELECT DISTINCT P.*, N.*
FROM Products P, NVD N
WHERE P.ID = N.ID
ORDER BY P.ID


SELECT DISTINCT N.*
FROM NVD N
WHERE VECTOR='NETWORK'
AND SCOREV3 > '9.0'
AND (ID LIKE '%1999%' OR SUMMARY LIKE '%default%')
ORDER BY ID

SELECT DISTINCT N.*
FROM NVD N
WHERE COUNT(N.ID) > 2
GROUP BY N.ID

SELECT COUNT(N.ID) rows FROM
(SELECT DISTINCT N.*
FROM NVD N, PRODUCTS P
WHERE N.ID = P.ID
AND CAST(N.SCOREV3 AS NUMERIC) > 0
AND P.PRODUCT='sunos' 
AND 

SELECT DISTINCT N.*, P.PRODUCT
FROM NVD N, PROnos' 
AND P.ID = N.ID

SELECT * 
FROM NVD N
WHERE N.ID = 'CVE-2002-0391'


SELECT DISTINCT P.PRODUCT, N.ID
FROM PRODUCTS P, NVD N
WHERE P.ID = N.ID
ORDER BY P.PRODUCT 